name: ScienceTools
version: 1.0
main: edu.whimc.sciencetools.ScienceTools
author: Jack Henhapl
description: Science Tools
commands:
  altitude:
    description: "Player's altitude"
  oxygen:
    description: "Oxygen level in the air of the player's location"
  pressure:
    description: "Air pressure of the player's location"
  temperature:
    description: "Temperature of the player's location"
  wind:
    description: "Wind speed of the player's location"
  sciencetools:
    description: Manage the ScienceTools plugin